let strings = {
  en: {
    'Wholesale': 'Wholesale',
    'tt-1-1': 'Increase Sales',
    'tt-1-2': 'Your shop and products are more visible for Tokopedia users.',
    'tt-2-1': 'Right on Target',
    'tt-2-2': 'TopAds helps you in reaching the right target market, through product searching, and product category.',
    'tt-3-1': 'Effective & Efficient',
    'tt-3-2': 'With TopAds, the result is worth your investment.',
    'tt-4': 'Read More',
    'tt-5': 'Promoted by TopAds.',
    'tt-6': 'Find out more.',
    'tt-7': 'Promoted by TopAds based on your interest.',
    'close': 'Close',
    'Favorite': 'Favorite',
    'Favorited': 'Favorited',
    'empty-prod': 'This shop has no product',
    'toast-fav': ' is added to your favorite list',
    'toast-unfav': ' is removed from your favorite list',
    'related': 'Related to this Item',
    'trend': 'Inspired by Your Shopping Trends',
    'visit-shop': 'Visit Shop',
    'BUY_NOW': 'Buy Now',
    'DONATE_NOW': 'Donate Now',
    'CHECK_MORE': 'Read More',
    'PAY_NOW': 'Pay Now',
    'first-buyer': 'Be the first buyer',
    'lang': 'en'
  },
  id: {
    'Wholesale': 'Grosir',
    'tt-1-1': 'Tingkatkan penjualan',
    'tt-1-2': 'TopAds membantu Anda untuk menarik calon pembeli secara lebih efektif. Toko dan produk Anda akan lebih mudah ditemukan oleh pengunjung Tokopedia.',
    'tt-2-1': 'Menjangkau dengan tepat',
    'tt-2-2': 'TopAds membantu Anda menjangkau calon pembeli yang sesuai, melalui pencarian produk dan penelusuran kategori produk.',
    'tt-3-1': 'Efektif dan Efisien',
    'tt-3-2': 'Dengan TopAds, hasil yang Anda harapkan sesuai dengan biaya yang Anda keluarkan.',
    'tt-4': 'Baca Selengkapnya',
    'tt-5': 'Promosi oleh TopAds.',
    'tt-6': 'Pelajari selengkapnya.',
    'tt-7': 'Promosi oleh TopAds yang muncul berdasarkan minat Anda.',
    'close': 'Tutup',
    'Favorite': 'Favoritkan',
    'Favorited': 'Favorit',
    'empty-prod': 'Tidak ada produk di toko ini',
    'toast-fav': ' ditambahkan ke dalam favorit.',
    'toast-unfav': ' dihapus dari favorit.',
    'related': 'Produk Terkait',
    'trend': 'Inspirasi dari Pembelian Anda',
    'visit-shop': 'Kunjungi Toko',
    'BUY_NOW': 'Beli Sekarang',
    'DONATE_NOW': 'Donasi Sekarang',
    'CHECK_MORE': 'Cek Selengkapnya',
    'PAY_NOW': 'Bayar Sekarang',
    'first-buyer': 'Jadilah pembeli pertama',
    'lang': 'id'
  }
};

export default strings;
